//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 25/05/2024 21:57:17
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace _405Found
{
    public partial class User {

        public User()
        {
            this.Books = new List<Books>();
            OnCreated();
        }

        public short User_Id { get; set; }
        public string? Name { get; set; }

        public string? SavedPassword { get; set; }

        public string? Email { get; set; }

        public virtual IList<Books> Books { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
        

    }

}
